### ISSUE TITLE
Run-Server.py error

### ISSUE THREAD

**Issue by Etol1LC** [Qirky/Polyglot#1]
Could not install on Mac.
When running from terminal "python run-server.py" I get an error like "no such file or directory".
I have download the polyglot master on my desktop. Everything else working properly. EspGrid and quarks installation. What am I missing?

**Comment by Qirky** [comment]
Are you in the right directory? You will need to use `cd` to change directory to the location of Polyglot. You can run the command `ls` to check the contents of your current directory, which will need to contain `run-client.py` and `run-server.py`

**Comment by Etol1LC** [comment]
this is the error I get:

MacBook-Pro-di-Claudio:polyglot claudiodonaggio$ python run-server.py
Password (leave blank for no password): 
Server running @ 192.168.1.3 on port 57890

python run-client.py
Terminated: 15
MacBook-Pro-di-Claudio:polyglot claudiodonaggio$ python run-client.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "/Users/claudiodonaggio/Desktop/polyglot/src/interface/conn_info.py", line 196, in store_data
    self.finish()
  File "/Users/claudiodonaggio/Desktop/polyglot/src/interface/conn_info.py", line 138, in finish
    self.client.setup(**self.options)
  File "/Users/claudiodonaggio/Desktop/polyglot/src/network/client.py", line 70, in setup
    except (ConnectionError, ConnectionRefusedError, AssertionError) as e:
NameError: global name 'ConnectionRefusedError' is not defined

By the way, does Polyglot work only with internet connection?

**Comment by Qirky** [comment]
What version of Python are you using? I think it only works with python 3. You can check by opening your terminal and typing python and pressing enter. This will open a python terminal and display the version number. Polyglot is still very much in alpha and I haven't completed documentation because of this.

It doesn't require internet connection but anyone who wants to connect to the Polyglot server needs to be on the same network

**Comment by Etol1LC** [comment]
Thanks can I Ask how do I update Python? I downloaded python 3 but when I am in the terminal It runs Ver. 2.7...

**Comment by Qirky** [comment]
Depending on your set up, you might be able to run `python3` in place of `python` which will run Python 3. If not set up, you can find some guides on the internet on how to do this e.g. https://www.maketecheasier.com/using-python-3-on-mac/. I'll make sure errors are thrown when using an incompatible version of Python

**Comment by Etol1LC** [comment]
This is what I get now:

Last login: Tue Jun 11 01:51:38 on ttys000
MBP-di-Claudio:~ claudiodonaggio$ cd desktop
MBP-di-Claudio:desktop claudiodonaggio$ cd polyglot
MBP-di-Claudio:polyglot claudiodonaggio$ python3 run-server.py
Password (leave blank for no password): 
Server running @ 192.168.1.3 on port 57890

python3 run-client.py
Terminated: 15
MBP-di-Claudio:polyglot claudiodonaggio$ python3 run-client.py

I don't know why, It keeps freezing python launcher which I have to force quit. When I do, it open the client console but as it opens it I get the error message in the terminal.

**Comment by Etol1LC** [comment]
The Console actually says:[Errno 61] Connection Refused

**Comment by Qirky** [comment]
Are you running the server and client in separate terminal windows or the  same one?
