### ISSUE TITLE
Error with run-server.py when running on remote server

### ISSUE THREAD

**Issue by berinhard** [Qirky/Polyglot#2]
Hi, thanks for you work =]

I'm trying to run a Polyglot's instance on my personal server. I'm getting an error with the `$DISPLAY` display. Here's my output from `run-server.py`:

```bash
$ python3 run-server.py 
Traceback (most recent call last):
  File "run-server.py", line 13, in <module>
    from src.network import PolyServer
  File "/home/berin/Polyglot-master/src/network/__init__.py", line 4, in <module>
    from .client import *
  File "/home/berin/Polyglot-master/src/network/client.py", line 3, in <module>
    from ..interface import *
  File "/home/berin/Polyglot-master/src/interface/__init__.py", line 2, in <module>
    from .interface import *
  File "/home/berin/Polyglot-master/src/interface/interface.py", line 31, in <module>
    ROOT = Tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

Any leads on how I can help with that? I've looked at [this StackOverflow](https://stackoverflow.com/questions/48924590/tkinter-setup-on-headless-server) post and it seems the fix requires a code change...

**Comment by ryan-kirkb** [comment]
Tbh it shouldn't really initialise the Tk instance in server mode - so that's a bit of careless programming on my end. However, I'm not really working on this at the moment but will try and have a look at some point in the near future.
